import Table from './table'
import {
    IProps,
    IColumnTotal,
    IColumns,
    IHeaders,
    ITotals,
    IColumnConfigStructure,
    IColumnHeaderStructure,
    ITotalList,
    IFreezeProps,
    IColumnConfig,
    IPageSizes,
    ISelected,
    IColumnHeader,
    IColumn,
    IrowActions,
    ILinksList,
    ItemFields,
    IFilterDataForRequest,
  } from './Models/table.models'
  import { StructureConfig } from './Models/table.enum'
  
  export {
    Table,
    IProps as ITableProps,
    IColumnTotal,
    IColumns,
    IHeaders,
    ITotals,
    IColumnConfigStructure,
    IColumnHeaderStructure,
    ITotalList,
    IFreezeProps,
    IColumnConfig,
    IPageSizes,
    ISelected,
    IColumnHeader,
    IColumn,
    IrowActions,
    ILinksList,
    StructureConfig,
    ItemFields,
    IFilterDataForRequest,
  }
